In [22]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
adult = fetch_ucirepo(id=2) 

# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 

# Combina X e y em um único DataFrame
df = pd.DataFrame(X)
df['target'] = y

# Exibe as primeiras linhas do DataFrame
print(df.head())

   age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country target  
0          2174             0              40  United-States  <=50K  
1             0             0             

In [23]:
display(df)

age         workclass  fnlwgt  education  education-num  \
0       39         State-gov   77516  Bachelors             13   
1       50  Self-emp-not-inc   83311  Bachelors             13   
2       38           Private  215646    HS-grad              9   
3       53           Private  234721       11th              7   
4       28           Private  338409  Bachelors             13   
...    ...               ...     ...        ...            ...   
48837   39           Private  215419  Bachelors             13   
48838   64               NaN  321403    HS-grad              9   
48839   38           Private  374983  Bachelors             13   
48840   44           Private   83891  Bachelors             13   
48841   35      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed                NaN  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
1                   White    Male             0             0              13   
2                   White    Male             0             0              40   
3                   Black    Male             0             0              40   
4                   Black  Female             0             0              40   
...                   ...     ...           ...           ...             ...   
48837               White  Female             0             0              36   
48838               Black    Male             0             0              40   
48839               White    Male             0             0              50   
48840  Asian-Pac-Islander    Male          5455             0              40   
48841               White    Male             0             0              60   

      native-country  target  
0      United-States   <=50K  
1      United-States   <=50K  
2      United-States   <=50K  
3      United-States   <=50K  
4               Cuba   <=50K  
...              ...     ...  
48837  United-States  <=50K.  
48838  United-States  <=50K.  
48839  United-States  <=50K.  
48840  United-States  <=50K.  
48841  United-States   >50K.  

[48842 rows x 15 columns]

In [24]:
df.iloc[:, 1]

0               State-gov
1        Self-emp-not-inc
2                 Private
3                 Private
4                 Private
               ...       
48837             Private
48838                 NaN
48839             Private
48840             Private
48841        Self-emp-inc
Name: workclass, Length: 48842, dtype: object

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

encoder_teste = LabelEncoder()
encoder_educacion = LabelEncoder()

teste = encoder_teste.fit_transform(df.iloc[:, 1])
teste

array([7, 6, 4, ..., 4, 4, 5])

In [26]:
df.iloc[0].values

array([39, 'State-gov', 77516, 'Bachelors', 13, 'Never-married',
       'Adm-clerical', 'Not-in-family', 'White', 'Male', 2174, 0, 40,
       'United-States', '<=50K'], dtype=object)

In [27]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'target'],
      dtype='object')

In [124]:
label_encoder_age = LabelEncoder()
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital_status = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_native_country = LabelEncoder()
label_encoder_target = LabelEncoder()

df2 = df.copy()


df2.iloc[:, 1] = label_encoder_workclass.fit_transform(df.iloc[:, 1])
df2.iloc[:, 3] = label_encoder_education.fit_transform(df.iloc[:, 3])
df2.iloc[:, 5] = label_encoder_marital_status.fit_transform(df.iloc[:, 5])
df2.iloc[:, 6] = label_encoder_occupation.fit_transform(df.iloc[:, 6])
df2.iloc[:, 7] = label_encoder_relationship.fit_transform(df.iloc[:, 7])
df2.iloc[:, 8] = label_encoder_race.fit_transform(df.iloc[:, 8])
df2.iloc[:, 9] = label_encoder_sex.fit_transform(df.iloc[:, 9])
df2.iloc[:, 13] = label_encoder_native_country.fit_transform(df.iloc[:, 13])
df2.iloc[:, 14] = label_encoder_target.fit_transform(df.iloc[:, 14])


for i in ['workclass', 'education','marital-status','race','sex', 'native-country', 'occupation', 'relationship', 'target' ]:
    df2[i] = df2[i].astype('int64')


df2.dtypes

import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Garantir que as colunas sejam numéricas
df2.iloc[:, [1, 3, 5, 6, 7, 8, 9, 13]] = df2.iloc[:, [1, 3, 5, 6, 7, 8, 9, 13]].apply(pd.to_numeric, errors='coerce')

# Agora aplique o OneHotEncoder com sparse_output=False
oneHotEncoder_dataframe = ColumnTransformer(
    transformers=[('OneHot', OneHotEncoder(sparse_output=False), [1, 3, 5, 6, 7, 8, 9, 13])],
    remainder='passthrough'
)

# Transforma os dados
df3 = oneHotEncoder_dataframe.fit_transform(df2)

In [125]:
df3.shape

(48842, 112)

In [126]:
from sklearn.preprocessing import StandardScaler
scalar_df = StandardScaler()
df4 = scalar_df.fit_transform(df3)

In [127]:
df4

array([[-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
        -0.03408696, -0.83464261],
       [-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
        -2.21303208, -0.83464261],
       [-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
        -0.03408696, -0.83464261],
       ...,
       [-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
         0.77292975,  0.19336431],
       [-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
        -0.03408696,  0.19336431],
       [-0.1976331 , -0.1737947 , -0.26193976, ..., -0.2171271 ,
         1.57994645,  2.24937814]])

# Divisão de treinamento e teste

In [134]:
from sklearn.model_selection import train_test_split

x_df_treinamento, x_df_teste, y_df_treinamento1, y_df_teste2 = train_test_split(df4, df4, test_size = 0.25, random_state=0)

In [136]:
x_df_treinamento.shape

(36631, 112)

# Salvando variaveis

In [144]:
import pickle

with open('censo.pkl', mode='wb') as f:
    pickle.dump([x_df_treinamento, y_df_treinamento1, x_df_teste, y_df_teste2], f)