In [6]:

# BIBLIOTECA PARA CRIAÇÃO DE ARRAYs, e metodos matematicos 
import numpy as np
from time import time as tp

inicio = tp()
lista = [i+1 for i in range(100000)]

for i in range(1,len(lista),1):
    soma = i+1
fim = tp()
display(fim-inicio)

0.012546300888061523

In [5]:
lista2 = np.array(lista)
display(lista2)

array([     1,      2,      3, ...,  99998,  99999, 100000])

In [31]:
# ndim: Retorna o número de dimensões (ou eixos) de um array NumPy.
# size: Retorna o número total de elementos em um array NumPy.
# shape: Retorna uma tupla representando as dimensões do array NumPy - LINHAS E COLUNAS.
# dtype: Retorna o tipo de dados dos elementos no array NumPy.



lista3 = np.array([[1,2,3],[1,4,5]])
display(lista3)

display('qtd elementos: ')
display(lista3.size)
# quantidade de linhas e colunas
display('qtd linhas e colunas: ')
display(lista3.shape)

#retorna tipo de dado
lista3.dtype




array([[1, 2, 3],
       [1, 4, 5]])

'qtd elementos: '

6

'qtd linhas e colunas: '

(2, 3)

dtype('int32')

In [35]:
# np.pi: Retorna o valor da constante matemática pi.
# np.sqrt(x): Retorna a raiz quadrada de x.


pi_ = np.pi
display(pi_)

raiz = np.sqrt(25)
display(raiz)






3.141592653589793

5.0

In [55]:
# np.zeros(shape): Cria um array preenchido com zeros.
# np.eye(N): Cria uma matriz identidade de ordem N.
# np.ones(shape): Cria um array preenchido com uns.
# np.arange(start, stop, step): Cria um array com valores espaçados uniformemente dentro de um intervalo especificado.
# np.vstack(tup): Empilha arrays verticalmente (vertical stack).
# np.linspace(start, stop, num): Cria um array com valores espaçados uniformemente dentro de um intervalo, especificando o número total de elementos.
zeros_array = np.zeros((2, 3))
display(zeros_array)

ones_array = np.ones((2,3))
display(ones_array)

ey = np.eye(5)
display(ey)

arrange_ = np.arange(1,5,3)
display(arrange_)

linspace_ = np.linspace(0,10,5)
display(linspace_)

array_1 = np.array((1,2,3,45,5))
array_2 = np.array((1,2,3,45,6))
vstack_ = np.vstack((array_1, array_2))
display(vstack_)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([1, 4])

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

array([[ 1,  2,  3, 45,  5],
       [ 1,  2,  3, 45,  6]])