In [2]:

# BIBLIOTECA PARA CRIAÇÃO DE ARRAYs, e metodos matematicos 
import numpy as np
from time import time as tp

inicio = tp()
lista = [i+1 for i in range(100000)]

for i in range(1,len(lista),1):
    soma = i+1
fim = tp()
display(fim-inicio)

0.02399468421936035

In [3]:
lista2 = np.array(lista)
display(lista2)

array([     1,      2,      3, ...,  99998,  99999, 100000])

In [4]:
# ndim: Retorna o número de dimensões (ou eixos) de um array NumPy.
# size: Retorna o número total de elementos em um array NumPy.
# shape: Retorna uma tupla representando as dimensões do array NumPy - LINHAS E COLUNAS.
# dtype: Retorna o tipo de dados dos elementos no array NumPy.

display(lista2.ndim)

lista3 = np.array([[1,2,3],[1,4,5]])
display(lista3)

display('qtd elementos: ')
display(lista3.size)
# quantidade de linhas e colunas
display('qtd linhas e colunas: ')
display(lista3.shape)

#retorna tipo de dado
lista3.dtype




1

array([[1, 2, 3],
       [1, 4, 5]])

'qtd elementos: '

6

'qtd linhas e colunas: '

(2, 3)

dtype('int32')

In [35]:
# np.pi: Retorna o valor da constante matemática pi.
# np.sqrt(x): Retorna a raiz quadrada de x.


pi_ = np.pi
display(pi_)

raiz = np.sqrt(25)
display(raiz)






3.141592653589793

5.0

In [65]:
# np.zeros(shape): Cria um array preenchido com zeros.
# np.eye(N): Cria uma matriz identidade de ordem N.
# np.ones(shape): Cria um array preenchido com uns.
# np.arange(start, stop, step): Cria um array com valores espaçados uniformemente dentro de um intervalo especificado.
# np.vstack(tup): Empilha arrays verticalmente (vertical stack).
# np.linspace(start, stop, num): Cria um array com valores espaçados uniformemente dentro de um intervalo, especificando o número total de elementos.

display('ZEROS E ONES')
zeros_array = np.zeros((2, 3))
display(zeros_array)

ones_array = np.ones((2,3))
display(ones_array)


ey = np.eye(5)
display(ey)

display('arranges, linspace e vstack')
arrange_ = np.arange(0,4,0.5)
display(arrange_)

linspace_ = np.linspace(0,10,5)
display(linspace_)

array_1 = np.array((1,2,3,45,5))
array_2 = np.array((1,2,3,45,6))
vstack_ = np.vstack((array_1, array_2))
display(vstack_)

'ZEROS E ONES'

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

'ONE'

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

'arranges, linspace e vstack'

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

array([[ 1,  2,  3, 45,  5],
       [ 1,  2,  3, 45,  6]])

In [9]:
# metodo COPY
# metodo reshape = 


vetor = np.arange(8)
display(vetor)

display(vetor.reshape(2,4)) # primeiro parametro é a linha, e o segundo as colunas 

vetor2 = vetor
vetor2[1] = 3

vetor3 = vetor.copy()
vetor3[0] = 10
display(vetor2)
display(vetor)
display(vetor3)


array([0, 1, 2, 3, 4, 5, 6, 7])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([0, 3, 2, 3, 4, 5, 6, 7])

array([0, 3, 2, 3, 4, 5, 6, 7])

array([10,  3,  2,  3,  4,  5,  6,  7])

In [25]:
# sum: Soma todos os elementos do array.
# min: Retorna o valor mínimo no array.
# max: Retorna o valor máximo no array.
# mean: Calcula a média dos elementos do array.
# cumsum: Retorna um array com a soma acumulada dos elementos.



import numpy as np

p = np.arange(8).reshape(2,4)**2
display(p)

display(p.max()) # default, pega o valor maximo

display(p.min(axis=1)) # retorna uma lista do menor de cada linha, vale para o max tambem


display('soma: ' + str(np.cumsum(p))) # soma acumulada

display('media ' + str(np.mean(p)))


array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

49

array([ 0, 16])

'soma: [  0   1   5  14  30  55  91 140]'

'media 17.5'

In [39]:
# pegando sub-array com fatiamento

b = np.arange(9).reshape(3,3)
display(b)

# Fatiamento para pegar elementos da primeira linha, começando do segundo elemento em diante
display(b[0,1:])

# Fatiamento para pegar sub-array a partir da segunda linha e da segunda coluna
display(
    b[1:, 1:] 
)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1, 2])

array([[4, 5],
       [7, 8]])