In [12]:
# IMPORTA A TIME 
from time import time

# CRIA UMA LISTA DE 0 A 10
a = list(range(10))
soma = 0 

# INICIA A CONTAGEM DO TEMPO
inicio = time()
for i in a:
    soma += i

# FINALIZA A CONTAGEM DO TEMPO
fim = time()
tempo = fim - inicio

# IMPRIME O RESULTADO DO TEMPO E DA SOMA
print(soma)
print(tempo)


55
0.0


In [18]:
import numpy as np

# cria um array uni-dimensional
lista = np.array([[1,1,1]])
print(lista.shape)

# cria um array bi-dimensional
lista2 = np.array([[1,1,1],[2,2,2]])
print(lista2.shape)

# imprime o tamanho do array
print(lista2.size)

# mostra a dimensão do array
print(lista2.ndim)



# O ARRAY SO PODE TER UM TIPO DE DADO

(1, 3)
(2, 3)
6


In [21]:
# cria o array np
operacao_np = np.array([[1,2,3],[4,5,6]])

# soma todos os elementos do array mais um
operacao_np2 = operacao_np + 1
print(operacao_np2 )

[[2 3 4]
 [5 6 7]]


In [28]:
# metodos numpy 


import numpy as np

# cria um array NumPy de zeros
zeros = np.zeros((3, 3))
print("Array de zeros:")
print(zeros)

# cria um array NumPy de uns
ones = np.ones((2, 2 * 10))
print("\nArray de uns:")
print(ones)

# cria um array NumPy de valores aleatórios
random = np.random.rand(2, 2)
print("\nArray de valores aleatórios:")
print(random)





# cria um array NumPy de valores igualmente espaçados
evenly_spaced = np.linspace(0, 10, 5)
print("\nArray de valores igualmente espaçados:")
print(evenly_spaced)

# cria um array NumPy de valores distribuídos normalmente
normally_distributed = np.random.normal(0, 1, (3, 3))
print("\nArray de valores distribuídos normalmente:")
print(normally_distributed)

# cria um array NumPy de matriz identidade
identity_matrix = np.eye(3)
print("\nMatriz identidade:")
print(identity_matrix)




Array de zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array de uns:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Array de valores aleatórios:
[[0.315083   0.80506592]
 [0.19597107 0.33996939]]

Array de valores igualmente espaçados:
[ 0.   2.5  5.   7.5 10. ]

Array de valores distribuídos normalmente:
[[ 0.00333975 -0.83153652  1.23498022]
 [ 1.55762713 -1.39644185  1.38409807]
 [ 0.09266645  2.21136647  1.10524036]]

Matriz identidade:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
## cria uma matriz unidimensional com valores de 0 a 11
arr = np.arange(12)

# transforma a matriz unidimensional em uma matriz bidimensional de 4 linhas e 3 colunas
arr_reshaped = arr.reshape(4, 3)

print(arr_reshaped)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
