In [12]:
# IMPORTA A TIME 
from time import time

# CRIA UMA LISTA DE 0 A 10
a = list(range(10))
soma = 0 

# INICIA A CONTAGEM DO TEMPO
inicio = time()
for i in a:
    soma += i

# FINALIZA A CONTAGEM DO TEMPO
fim = time()
tempo = fim - inicio

# IMPRIME O RESULTADO DO TEMPO E DA SOMA
print(soma)
print(tempo)


55
0.0


In [18]:
import numpy as np

# cria um array uni-dimensional
lista = np.array([[1,1,1]])
print(lista.shape)

# cria um array bi-dimensional
lista2 = np.array([[1,1,1],[2,2,2]])
print(lista2.shape)

# imprime o tamanho do array
print(lista2.size)

# mostra a dimensão do array
print(lista2.ndim)



# O ARRAY SO PODE TER UM TIPO DE DADO

(1, 3)
(2, 3)
6


In [21]:
# cria o array np
operacao_np = np.array([[1,2,3],[4,5,6]])

# soma todos os elementos do array mais um
operacao_np2 = operacao_np + 1
print(operacao_np2 )

[[2 3 4]
 [5 6 7]]


In [24]:
# metodos numpy 


import numpy as np

# cria um array NumPy de zeros
zeros = np.zeros((3, 3))
print("Array de zeros:")
print(zeros)

# cria um array NumPy de uns
ones = np.ones((2, 2 * 10))
print("\nArray de uns:")
print(ones)

# cria um array NumPy de valores aleatórios
random = np.random.rand(2, 2)
print("\nArray de valores aleatórios:")
print(random)





Array de zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array de uns:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Array de valores aleatórios:
[[0.82326456 0.58646503]
 [0.54641969 0.43619187]]

Array de valores igualmente espaçados:
[ 0.   2.5  5.   7.5 10. ]

Array de valores distribuídos normalmente:
[[-0.30042763 -1.0460035   0.53527765]
 [ 1.57495084 -1.14477719  0.46983302]
 [-0.6344338   0.60065226  0.78910949]]

Matriz identidade:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
## cria uma matriz unidimensional com valores de 0 a 11
arr = np.arange(12)

# transforma a matriz unidimensional em uma matriz bidimensional de 4 linhas e 3 colunas
arr_reshaped = arr.reshape(4, 3)

print(arr_reshaped)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
