In [12]:
# IMPORTA A TIME 
from time import time

# CRIA UMA LISTA DE 0 A 10
a = list(range(10))
soma = 0 

# INICIA A CONTAGEM DO TEMPO
inicio = time()
for i in a:
    soma += i

# FINALIZA A CONTAGEM DO TEMPO
fim = time()
tempo = fim - inicio

# IMPRIME O RESULTADO DO TEMPO E DA SOMA
print(soma)
print(tempo)


55
0.0


In [18]:
import numpy as np

# cria um array uni-dimensional
lista = np.array([[1,1,1]])
print(lista.shape)

# cria um array bi-dimensional
lista2 = np.array([[1,1,1],[2,2,2]])
print(lista2.shape)

# imprime o tamanho do array
print(lista2.size)

# mostra a dimensão do array
print(lista2.ndim)



# O ARRAY SO PODE TER UM TIPO DE DADO

(1, 3)
(2, 3)
6


In [19]:
## cria uma matriz unidimensional com valores de 0 a 11
arr = np.arange(12)

# transforma a matriz unidimensional em uma matriz bidimensional de 4 linhas e 3 colunas
arr_reshaped = arr.reshape(4, 3)

print(arr_reshaped)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
